### PR TITLE
AES cleanup

### PR DESCRIPTION
**Pull request by dcousens**
I wanted to vet this code.

It was a nightmare with the ternary jumbles everywhere and use of comma operator inline in those expressions.

Review is easier commit-by-commit.

### CODE REVIEW

**Comment by dcousens** [comment]
Added a bench suite to ensure there is no regression in performance. [and there isn't]

**Comment by dcousens** [comment]
+3% performance boost in the end,  not much,  but oh god the readability.

**Comment by dcousens** [comment]
@fanatid @calvinmetcalf - this PR is ready to review :+1:

**Comment by calvinmetcalf** [comment]
you need to leave a stub at `/modes` as it's relied upon in browserify-cipher

**Comment by dcousens** [comment]
I wasn't sure if `/modes` was public API,  good to know :+1:

**Comment by dcousens** [comment]
@calvinmetcalf it should still work,  `/modes/index.js` exists and exports everything necessary

**Comment by dcousens** [comment]
ping @calvinmetcalf

**Comment by calvinmetcalf** [comment]
have you linked locally to test with  browserify-cipher? what is the benchmark difference (if any), also we have a failing test

**Comment by dcousens** [comment]
> have you linked locally to test with browserify-cipher

Why would I need to?

> also we have a failing test

Indeed,  a type-error of some sort.
I'll investigate...

**Comment by calvinmetcalf** [comment]
> have you linked locally to test with browserify-cipher

to double check the moved file doesn't break things, probably doesn't but
we should check

**Comment by dcousens** [comment]
Will do - tomorrow.
If it works, and I fix the test [assuming something trivial],  good to merge?

**Comment by calvinmetcalf** [comment]
yup awk

**Comment by dcousens** [comment]
Everything works :+1:

**Pull request merged**
