### PR TITLE
add LICENSE amendments as suggested

### PR DESCRIPTION
**Pull request by dcousens**
An attempt at following up https://github.com/crypto-browserify/browserify-aes/issues/43

### CODE REVIEW

**Comment by dcousens** [comment]
@calvinmetcalf I made an attempt,  but it'd be good if you could verify if these attributions and LICENSE's match the derivations that you made.

I am not a lawyer,  merely trying to ensure credit is given where required.

**Comment by dcousens** [comment]
@bastien-roucaries if you could review this too that'd be great!

**Comment by calvinmetcalf** [comment]
i did this a very long time ago but this seems fine

**Comment by dcousens** [comment]
@calvinmetcalf if you think its' good,  merge + publish!  I am not part of the org :+1:

**Pull request merged**
