### PR TITLE
Fix #44 test issues

### LINKED ISSUE #44: Test suite fail under node v4.8.2
Test suite fail see txt file joinded. Using master and lasted version
[fail.txt](https://github.com/crypto-browserify/browserify-aes/files/1033563/fail.txt)

### PR DESCRIPTION
**Pull request by dcousens**
https://github.com/crypto-browserify/browserify-aes/commit/a5ca6e963aeb9bf4cd23d38403cb137a742945e5 was the culprit AFAIK

I added Node 8 to travis... it is exploding all the way back to `v1.0.0`... sigh.

### CODE REVIEW

**Comment by dcousens** [comment]
ping @pravi

**Comment by pravi** [comment]
Test suite itself was failing with error before. Now test suite is completing, but some tests are failing. See the log.

**Comment by pravi** [comment]
```
```
$ nodejs -v
v6.9.2
buffer-xor 2.0.1
```

**Comment by dcousens** [comment]
@pravi what?  the tests aren't failing for the required `buffer-xor`.  `buffer-xor^2.0.0` is not compatible with what we need.

**Comment by dcousens** [comment]
Fixed in https://github.com/crypto-browserify/browserify-aes/issues/44

**Comment by pravi** [comment]
I can confirm that. For now we'll use buffer-xor 1.0.3. But is there a plan to update it to 2.0?

**Comment by dcousens** [comment]
@pravi no,  it is fundamentally different,  we'd simply end up rolling our own code instead.

**Pull request merged**
