### PR TITLE
correctly handle incremental base64 data

### PR DESCRIPTION
**Pull request by calvinmetcalf**
fixes crypto-browserify/crypto-browserify#132

### CODE REVIEW

**Comment by jprichardson** [comment]
ACK. Nice work!

**Comment by donavon** [comment]
:+1: Good job!

**Comment by donavon** [comment]
Any change of getting a new patch release out to npm soon-ish?

**Comment by calvinmetcalf** [comment]
should already be up there

**Comment by dcousens** [comment]
Well done @calvinmetcalf,  to elaborate on the underlying issue,  the existing node code would allow for you to feed incomplete base64 strings in?

**Comment by calvinmetcalf** [comment]
so when binary data is encoded in base64 if the length isn't divisible by 3 it is padded with `=`, node will cache the last 1 or 2 bytes to avoid trailing `=`'s so you can concat the resulting strings and feed it back in

**Comment by dcousens** [comment]
So, it allows you to feed in incomplete base64?

**Comment by calvinmetcalf** [comment]
It shouldn't make a difference for feeding it stand alone results in base64 because it should be able to decode those stand alone fragments fine, it's concatenating incomplete fragments so that only the final chunk had the base64 padding

**Pull request merged**
