### PR TITLE
fixes #26- issues with encoding beyond base64

### LINKED ISSUE #26: Long utf8 plaintexts get corrupted when decrypting.
Here's the functions I wrote.
```javascript
var Crypto = require('crypto-browserify');

var encrypt = function (txt, passwd, salt) {
  salt = salt || "テストです。この塩を変えた方が安全です。";
  var cipher = Crypto.createCipher('aes-256-cbc',Crypto.pbkdf2Sync(passwd, salt, 8192, 32, 'sha256'));
  var result = cipher.update(txt, 'utf8', 'base64')
  result += cipher.final('base64')
  cipher = null;
  txt = null;
  passwd = null;
  salt = null;
  return result;
};
var decrypt = function (enc, passwd, salt) {
  salt = salt || "テストです。この塩を変えた方が安全です。";
  var decipher = Crypto.createDecipher('aes-256-cbc',Crypto.pbkdf2Sync(passwd, salt, 8192, 32, 'sha256'));
  try {
    var result = decipher.update(enc, 'base64', 'utf8')
    result += decipher.final('utf8')
  } catch(e) {
    return null;
  };
  decipher = null;
  enc = null;
  passwd = null;
  salt = null;
  return result;
};

var enc = encrypt("ふっかつ　あきる　すぶり　はやい　つける　まゆげ　たんさん　みんぞく　ねほりはほり　せまい　たいまつばな　ひはん","a","a");
// gives me "95XLoYZrLtCzx/WDzQ+G5vA293ynWpBhNRyIUV2CTZACSR4HKwWCAIIUklewk/bmTeFvzk7X0yRAQVXnkgwgMfAVs5uDkw6naSWN5akWwLYbEZurjFaQcdncy9wvmmS2c8gOFo90yWNSrQRKlhifmi5ibgVF3HgvDTcksofTjUzzFxaRqINZuHjcVZMiggAAX1etUgZdSM8O33ciWwyv2YBo2EsJOb9z1KyMNXaICK2PtC505Sru9W9q1mnPQOAA"

var dec = decrypt(enc, "a", "a");
// gives me "��" (which is two utf8 characters of "\uFFFD")
```

If you could:
a. tell me if my functions are written wrong, if that's the case.
b. fix the problem if it is a problem with the library.

I would greatly appreciate it. Thanks.

btw, if I just encrypt a short string like ふっかつ and decrypt it it comes out fine.

Also: The text I am trying above is 60 utf8 3 byte characters, but I tried 180 "a"s together and it decrypted fine. I think it's a problem with the base64 >> utf8 conversion or something.

### PR DESCRIPTION
**Pull request by calvinmetcalf**
relies on the string decoder module to accurately decode things, also correctly throws errors (like node) if you switch the encoding up.

### CODE REVIEW

**Comment by dcousens** [comment]
Encoding seems to be a constant problem.

**Comment by calvinmetcalf** [comment]
@dcousens this is the truth, but we're now using the built in encoding stuff so it should be (hopefully) less of OUR issue

**Comment by dcousens** [comment]
ACK,  thanks @calvinmetcalf

**Comment by dcousens** [comment]
released browserify-aes@1.0.4

**Comment by dabura667** [comment]
Thanks guys!

@calvinmetcalf 10000 bits @changetip

**Comment by changetip** [comment]
Hi @calvinmetcalf, @dabura667 sent you a tip worth 10000 bits ($2.30), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/899164)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Pull request merged**
