### PR TITLE
Add LICENSE and author info.

### PR DESCRIPTION
**Pull request by mkillianey**

### CODE REVIEW

**Comment by dcousens** [comment]
Same point as in https://github.com/crypto-browserify/browserify-sign/pull/21

**Comment by mkillianey** [comment]
Changed copyright line in LICENSE to "browserify-aes contributors" as per conversation in https://github.com/crypto-browserify/browserify-sign/pull/21

**Comment by dcousens** [comment]
Thanks @mkillianey

**Comment by dcousens** [comment]
@calvinmetcalf feel free to adjust this as needed.
Not sure if you wanted https://github.com/crypto-browserify/browserify-sign/commit/153a93f0f05c4368c76789df2df4a09ea455a8a9 across most of the packages you initialized?

**Pull request merged**
