### PR TITLE
modes as json file

### PR DESCRIPTION
**Pull request by fanatid**
Related issue: #34

### CODE REVIEW

**Comment by dcousens** [comment]
LGTM

**Comment by dcousens** [comment]
Nicely done @fanatid

**Comment by calvinmetcalf** [comment]
we probably want to add a .json extension to where it's imported

**Comment by fanatid** [comment]
@calvinmetcalf fixed in #36

**Comment by dcousens** [comment]
@calvinmetcalf AFAIK that isn't necessary?

**Comment by calvinmetcalf** [comment]
not technically for browserify, but it helps for webpack

**Pull request merged**
