### PR TITLE
Use create-hash to avoid needing DI of crypto

### PR DESCRIPTION
**Pull request by ForbesLindesay**
By using crate-hash we can avoid the complicated DI of crypto.  Ultimately this could then be loaded by crypto-browserify as:

```js
var aes = require('browserify-aes');
exports.createCipher = exports.Cipher = aes.createCipher;
exports.createCipheriv = exports.Cipheriv = aes.createCipheriv;
exports.createDecipher = exports.Decipher = aes.createDecipher;
exports.createDecipheriv = exports.Decipheriv = aes.createDecipheriv;
exports.listCiphers = exports.getCiphers = aes.getCiphers;
```

Like with create-hash, this ensures that the regular `crypto` module is used on the server side.

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
beat me to it :+1: (though this is waiting on crypto-browserify/crypto-browserify#109

**Comment by calvinmetcalf** [comment]
we can even go a bit farther #17

**Comment by calvinmetcalf** [comment]
closing in favor of #17 which includes this

**Comment by ForbesLindesay** [comment]
Awesome :)

**Comment by calvinmetcalf** [comment]
published as 1.0.0

**Pull request closed without merging**
